### ISSUE TITLE
Fonts are missing

### ISSUE THREAD

**Issue by azimidev** [mdhheydari/iransans-fontface-bower#1]
The font folder is empty

**Comment by 0xC0D3D00D** [comment]
@hassanazimi, I mentioned in the README that the fonts are licensed and you should obtain it yourself from [the font creator's website](http://fontiran.com/).

If you don't like to purchase any fonts. I suggest [these open source free fonts](https://github.com/rastikerdar). but you need to write a library like this which is fairly easy.
